// <auto-generated />
namespace QBA.Qutilize.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MakingEndTimeNullableInDailyTaskTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakingEndTimeNullableInDailyTaskTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201902050818111_MakingEndTimeNullableInDailyTaskTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
