// <auto-generated />
namespace QBA.Qutilize.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class configuringUserProjectMappingTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(configuringUserProjectMappingTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201902011315387_configuringUserProjectMappingTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
